version: '3.3'

services:

  nodeexpressapp:
    image: zogspat/noderecipe:0.0.16
    ports:
      - "80:8090"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: recipes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: {}
